FLARE/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('forecast.urls')),
    path('accounts/', include('users.urls')),
    path('community/', include('community.urls')),
    path('weather-alert/', include('weather_alert.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

community/urls.py
from django.urls import path
from .views import community_home, forum, create_forum, upload_media


urlpatterns = [
    path('', community_home, name='community-home'),
    path('forum/<str:forum_id>/', forum, name='forum'),
    path('create-forum/', create_forum, name='create-forum'),
    path('upload_media/', upload_media, name='upload-media')
]

community/models.py
import uuid
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

# Regions model
class Region(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

# forum model
class Forum(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    region = models.ForeignKey(Region, on_delete=models.SET_NULL, null=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    members = models.ManyToManyField(User, related_name='forum_members')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated_at', '-created_at']

    def __str__(self):
        return self.name

# Forum Media model
class Media(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    file = models.FileField(upload_to='forum/images/')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    

# Forum Messages model
class Message(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    forum = models.ForeignKey(Forum, on_delete=models.CASCADE)
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(blank=True, null=True)
    media = models.ForeignKey(Media, on_delete=models.SET_NULL, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

community/forms.py
from django import forms
from .models import Forum


# Region form
class CreateForumForm(forms.ModelForm):
    class Meta:
        model = Forum
        fields = ['name', 'description', 'region']

community/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from .models import Region, Forum, Media, Message
from .forms import CreateForumForm
from weather_alert.models import WeatherAlert

# Community home view
@login_required
def community_home(request):
    form = CreateForumForm()
    # regions = Region.objects.all()
    # forums = Forum.objects.all()
    q = request.GET.get('q') if request.GET.get('q') else ''
    regions = Region.objects.filter(name__icontains=q)
    forums = Forum.objects.filter(
        Q(region__name__icontains=q) |
        Q(name__icontains=q) |
        Q(description__icontains=q)
    )
    weather_alerts = WeatherAlert.objects.all()
    context = {
        'regions': regions,
        'forums': forums,
        'weather_alerts': weather_alerts,
        'form': form,
    }

    return render(request, 'community/index.html', context)

# Create forum view
@login_required
def create_forum(request):
    form = CreateForumForm()
    regions = Region.objects.all()
    
    if request.method == 'POST':
        region_name = request.POST.get('region').capitalize()
        region, created = Region.objects.get_or_create(name=region_name)

        new_forum = Forum.objects.create(
            name = request.POST.get('name'),
            description = request.POST.get('description'),
            region = region,
            owner = request.user,
        )
        new_forum.members.add(request.user)
        return redirect('community-home')

    context = {
        'regions': regions,
        'form': form,
    }
    return redirect('community-home', context)


# forum view
@login_required
def forum(request, forum_id):
    forum = Forum.objects.get(id=forum_id)
    region = forum.region
    region_forums = Forum.objects.filter(region=region)
    forum_messages = Message.objects.filter(forum=forum)
    context = {
        'forum': forum,
        'region_forums': region_forums,
        'forum_messages': forum_messages,
    }
    return render(request, 'community/forum.html', context)

# Handle media upload from websocket
@login_required
def upload_media(request):
    if request.method == 'POST':
        media = Media(file=request.FILES['file'])
        media.save()
        return JsonResponse({'media_url': media.file.url})
    return JsonResponse({'error': 'Invalid request'}, status=400)

templates/community/forum.html
{% extends 'base.html' %}
{% block title %}FLARE - Forum{% endblock title %}
{% block css %}
{% load static %}
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">

    <link rel="stylesheet" href="{% static 'styles/forum.css' %}">
{% endblock css %}
{% block content %}
    <div class="container-fluid py-5">
        <div class="row justify-content-center h-100">
            <div class="col-md-4 col-xl-3 chat">
                <div class="card mb-sm-3 mb-md-0 contacts_card">
                    <div class="card-hearder">
                        <div class="input-group">
                            <input type="text" placeholder="Search..." name="" class="form-control search">
                            <div class="input-group-prepend">
								<span class="input-group-text search_btn"><i class="fas fa-search"></i></span>
							</div>
                        </div>
                    </div>
                    <div class="card-body contacts_body">
                        <ui class="contacts">
                            {% for forum in region_forums %}
                            <li class="active">
                                <a href="{% url 'forum' forum.id %}">
                                    <div class="d-flex bd-highlight">
                                        <div class="user_info">
                                            <span>{{forum.name}}</span>
                                            <p>{{ forum.description }}</p>
                                        </div>
                                    </div>
                                </a>
                            </li>
                            {% endfor %}
                        </ui>
                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>
            <div class="col-md col-xl-6 chat">
                <div class="card">
                    <div class="card-header msg_head">
                        <div class="d-flex bd-highlight">
                            <div class="user_info">
                                <span>{{forum.name}}</span>
                                <p>{{forum.description}}</p>
                            </div>
                        </div>
                    </div>
                    <div class="card-body msg_card_body">
                        {% for message in forum_messages %}
                            {% if message.sender == request.user %}
                            <div class="d-flex justify-content-end mb-4">
                                <div class="msg_cotainer sender_msg">
                                    {% if message.media %}
                                    <img src="{{message.media.file.url}}" class="img_fluid msg_image">
                                    {% endif %}
                                    {% if message.text %}
                                    {{message.text}}
                                    {% endif %}
                                    <span class="msg_time_send">{{message.created_at| timesince}}</span>
                                </div>
                            </div>
                            {% else %}
                            <div class="d-flex justify-content-start mb-4">
                                <div class="img_cont_msg">
                                    <img src="{{message.sender.avatar.url}}" class="rounded-circle user_img_msg">
                                </div>
                                <div class="msg_cotainer">
                                    {% if message.media %}
                                    <img src="{{message.media.file.url}}" class="img_fluid msg_image">
                                    {% endif %}
                                    {% if message.text %}
                                    {{message.text}}
                                    {% endif %}
                                    <span class="msg_time_send">{{message.created_at| timesince}}</span>
                                </div>
                            </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div class="card-footer">
                        <form id="chat-form">
                            {% csrf_token %}
                            <input type="file" class="form-control" id="formFile" multiple>
                            <div class="input-group">
                                <textarea class="form-control type_msg" id="text" placeholder="Type your message..."></textarea>
                                    <button type="submit" class="btn btn-primary">Send</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}
{% block script %}
    <script>
        const forumId = "{{ forum.id }}";
        const userName = "{{ request.user.username }}";
    
        const chatSocket = new WebSocket(
            'ws://' + window.location.host + '/ws/forum/' + forumId + '/'
        );

        const chatContainer = document.querySelector('.msg_card_body');

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);

            // determine if message is from the current user
            const isSender = data.sender === userName;

            // create message html
            let messageHtml = '';
            let timeDisplay = data.created_at == '0 minutes' ? 'now' : data.created_at;
            if (isSender) {
                messageHtml = `
                    <div class="d-flex justify-content-end mb-4">
                        <div class="msg_cotainer sender_msg">
                            ${data.media_url ? `<img src="${data.media_url}" class="img_fluid msg_image">` : ''}
                            ${data.message ? data.message : ''}
                            <span class="msg_time_send">${timeDisplay}</span>
                        </div>
                    </div>
                `;
            } else {
                messageHtml = `
                    <div class="d-flex justify-content-start mb-4">
                        <div class="img_cont_msg">
                            <img src="https://static.turbosquid.com/Preview/001292/481/WV/_D.jpg" class="rounded-circle user_img_msg">
                        </div>
                        <div class="msg_cotainer">
                            ${data.media_url ? `<img src="${data.media_url}" class="img_fluid msg_image">` : ''}
                            ${data.message ? data.message : ''}
                            <span class="msg_time">${timeDisplay}</span>
                        </div>
                    </div>
                `;
            }
            chatContainer.innerHTML += messageHtml
        

            // Scroll to the bottom of the chat container
            chatContainer.scrollTop = chatContainer.scrollHeight;
        };

        document.getElementById('chat-form').onsubmit = function(e) {
            e.preventDefault();
            const messageInput = document.getElementById('text');
            const message = messageInput.value;
            const mediaInput = document.getElementById('formFile');
            const mediaFile = mediaInput.files[0];

            if (mediaFile) {
                const formData = new FormData();
                formData.append('file', mediaFile);
                fetch('/community/upload_media/', {
                    method: 'POST',
                    body: formData,
                    headers: {
                        'X-CSRFToken': document.getElementsByName('csrfmiddlewaretoken')[0].value,
                    },
                })
                .then(response => response.json())
                .then(data => {
    
                    console.log("Media URL:", data.media_url);
    
                    chatSocket.send(JSON.stringify({
                        'message': message,
                        'media_url': data.media_url,
                    }));
                });
                } else {
                    chatSocket.send(JSON.stringify({
                        'message': message,
                        'media_url': '',
                    }));
                }
        
                messageInput.value = '';
                mediaInput.value = '';
        };

    </script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- <script src="script.js"></script> -->
{% endblock script %}

templates/community/index.html
{% extends 'base.html' %}
{% block title %}FLARE - Community{% endblock title %}
{% block content %}
{% load widget_tweaks %}
<div class="container">
    <div class="row">
        <div class="col-sm-3 d-none d-sm-block p-2">
          <h3 class="pt-2 fs-4 fw-bold">Regions</h3>
            <div class="card auth-card card-scroll">
              <div class="p-3">
                  <ul class="list-group">
                    {% for region in regions %}
                      <li class="d-flex justify-content-between align-items-start pb-4 fs-5">
                        <div class="ms-2 me-auto">
                          <div class="text-white fw-medium">{{region.name}}</div>
                        </div>
                        <span class="badge text-bg-light rounded-pill">{{region.forum_set.all.count}}</span>
                      </li>
                    {% endfor %}
                  </ul>
              </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="container">
                <div class="d-flex justify-content-between py-4">
                    <h3 class="fs-4 fw-bold" >Forums</h3>
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                      New Forum
                    </button>
                    
                    <!-- Modal -->
                    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                      <div class="modal-dialog text-black">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h4 class="modal-title fs-5" id="exampleModalLabel">Create New Forum</h4>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                          </div>
                          <div class="modal-body">
                            <form action="{% url 'create-forum' %}" method="POST">
                              {% csrf_token %}
                              <div class="mb-3">
                                <label for="region" class="form-label">Enter a Region</label>
                                <input type="text" name="region" value="" class="form-control" id="region" aria-describedby="region" list="region-list" required>
                                <datalist id="region-list">
                                  <select name="" id="">
                                    {% for region in regions %}
                                        <option value="{{region.name}}"></option>
                                    {% endfor %}
                                  </select>
                                </datalist>
                              </div>
                              <div class="mb-3">
                                <label for="forumname" class="form-label">Forum {{field.form.lael}}</label>
                                {% render_field form.name class="form-control" id="forumname" aria-describedby="forum" %}
                              </div>
                              <div class="mb-3">
                                <label for="forumdescription" class="form-label">{{field.form.label}}</label>
                                {% render_field form.description class="form-control type_msg" id="forumdescription" aria-describedby="forumdescription" %}
                              </div>

                              <button type="submit" class="btn btn-primary col-lg-12 col-12 mt-2 mb-3">Create</button>
                            </form>
                          </div>
                        </div>
                      </div>
                    </div>
                </div>
                <div class="forum-list">
                  {% for forum in forums %}
                  <div class="card auth-card text-white mb-4">
                  <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center">
                      <div class="d-flex py-2 align-items-center">
                        <img src="{{forum.owner.avatar.url}}" alt="user" class="rounded-circle" width="40" height="40">
                        <h6 class="ms-2 pt-2">@{{forum.owner.username}}</h6>
                      </div>
                      <small>{{forum.created_at|timesince}}</small>
                    </div>
                    <a href="{% url 'forum' forum.id %}" class="text-decoration-none text-white">
                      <h5 class="card-title">{{forum.name}}</h5>
                      <p class="card-text">{{forum.description}}</p>
                    </a>
                    </div>
                    <div class="card-footer d-flex justify-content-between align-items-center">
                      <div class="icon">
                        <i class="fa-solid fa-user-group"></i>
                        <span>{{forum.members.count}}</span>
                      </div>
                      <span class="badge text-bg-secondary">{{forum.region}}</span>
                    </div>
                  </div>
                  {% endfor %}
                </div>
            </div>
        </div>
        
        <div class="col-sm-4 col-md-3">
            <div class="card auth-card text-white my-4 card-scroll">
              <h5 class="card-header fw-bold fs-4">Weather Alerts</h5>
              <div class="card-body">
                {% if weather_alerts %}
                {% for alert in weather_alerts %}
                <div class="card text-whit bg-light mb-3">
                  <div class="card-body">
                    <div class="d-flex justify-content-between align-items-start pb-4 fs-5">
                      <span class="badge text-bg-secondary">{{alert.region}}</span>
                        <small class="fs-6 text-muted">{{alert.created_at| timesince}}</small>
                    </div>
                    <p class="card-text">{{alert.title}}</p>
                  </div>
                </div>
                  {% endfor %}
                  {% else %}
                  <h5>No Weather Alerts Availabe</h5>
                  {% endif %}
              </div>
    
            </div>
            
        </div>
    </div>
</div>
{% endblock content %}